### ISSUE TITLE
How can I reproduce experimental results?

### ISSUE THREAD

**Issue by hyoonsoo** [decisionforce/CoPO#25]
Hello, I am very impressed with the CoPO project. Thank you for sharing a great paper and code.
I wanted to see the trained multi-agent, so I visualized it using the weight stored in copo_code/copo/best_checkpoint/ and copo_code/vis.py. file. (without any modifications)
However, unlike the paper, I was able to render agents with lower performance(lower succeess rate).
How should I modify the code to see the higher performance of agents like your paper?
I look forward to your reply. Thank you.

**Comment by pengzhenghao** [comment]
Hi Yoonsoo,

Finally, I finished benchmarking the results of various MARL algorithms in MetaDrive MARL environments. Please kindly refer to this page:

https://github.com/metadriverse/metadrive-benchmark/tree/main/MARL

And I also upload latest trained models so you can run it to visualize the behaviors! This time I don’t find any performance discrepancy in the latest models (which proved that the performance discrepancy is due to the update of environment)!

https://github.com/decisionforce/CoPO#visualization

Thanks!

**Comment by hyoonsoo** [comment]
I've been waiting for a new update!!
Thank you for your kind reply.

**Comment by pengzhenghao** [comment]
As I updated last month, the result is in https://github.com/metadriverse/metadrive-benchmark/tree/main/MARL

Do you have any question?

**Comment by XilunZhangRobo** [comment]
Hi Zhenghao, 
I trained the intersection using torch copo (train_copo.py) and tried to evaluate the performance using copo_code/new_vis.py. 
However, it gives unpickled = pickle.loads(data) TypeError: an integer is required (got type bytes). 
I used the file that was stored in TEST/CoPOTraininger_Multi.../checkpoint_000440/algorithm_state.pkl. Did I use the wrong pkl file?

**Comment by pengzhenghao** [comment]
> Hi Zhenghao,
> I trained the intersection using torch copo (train_copo.py) and tried to evaluate the performance using copo_code/new_vis.py.
> However, it gives unpickled = pickle.loads(data) TypeError: an integer is required (got type bytes).
> I used the file that was stored in TEST/CoPOTraininger_Multi.../checkpoint_000440/algorithm_state.pkl. Did I use the wrong pkl file?

Hi @XilunZhangRobo 

Let's discuss this in a new issue.
